FLL/Models/Rating.cs
using System.ComponentModel.DataAnnotations;

namespace FLL.Models;

public class Rating
{
    public Guid RatingId { get; set; }
    public Guid UserId { get; set; }
    public Guid ExhibitId { get; set; }
    [Range(1, 5)] public double RatingValue { get; set; }
    public string? Message { get; set; }
}

FLL/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FLL.Data;
using FLL.Models;
using Microsoft.AspNetCore.Authorization;

namespace FLL.Controllers
{
    public class RatingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RatingsController(ApplicationDbContext context)
        {
            _context = context;
        }


        [Authorize]
        // GET: Ratings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rating.ToListAsync());
        }


        [Authorize]
        // GET: Ratings/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rating = await _context.Rating
                .FirstOrDefaultAsync(m => m.RatingId == id);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }


        [Authorize]
        // GET: Ratings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ratings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid exhibitId, Guid userId, double ratingValue)
        {
            if (ModelState.IsValid)
            {
                var rating = await _context.Rating.FirstOrDefaultAsync(r => r.UserId == userId);

                if (rating is null)
                {
                    rating = new Rating()
                    {
                        RatingValue = ratingValue,
                        ExhibitId = exhibitId,
                        UserId = userId
                    };
                    _context.Add(rating);
                }
                else
                {
                    rating.ExhibitId = exhibitId;
                    rating.RatingValue = ratingValue;
                }

                await _context.SaveChangesAsync();
                return RedirectToAction("LeaveMessage", rating);
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult LeaveMessage(Rating rating)
        {
            return View(rating);
        }


        [Authorize]
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> UpdateRatingMessage(Guid ratingId, Rating ratingForm)
        {
            var rating = await _context.Rating.FirstOrDefaultAsync(r => r.RatingId == ratingId);

            if (rating is not null)
            {
                rating.Message = ratingForm.Message;
            }

            await _context.SaveChangesAsync();

            return View("ThankYou");
        }


        [Authorize]
        // GET: Ratings/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rating = await _context.Rating.FindAsync(id);
            if (rating == null)
            {
                return NotFound();
            }
            return View(rating);
        }


        [Authorize]
        // POST: Ratings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("RatingId,UserId,ExhibitId,RatingValue,Message")] Rating rating)
        {
            if (id != rating.RatingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rating);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RatingExists(rating.RatingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rating);
        }


        [Authorize]
        // GET: Ratings/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rating = await _context.Rating
                .FirstOrDefaultAsync(m => m.RatingId == id);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }


        [Authorize]
        // POST: Ratings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var rating = await _context.Rating.FindAsync(id);
            if (rating != null)
            {
                _context.Rating.Remove(rating);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RatingExists(Guid id)
        {
            return _context.Rating.Any(e => e.RatingId == id);
        }
    }
}

FLL/Views/Ratings/Create.cshtml
@model FLL.Models.Rating

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Rating</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ExhibitId" class="control-label"></label>
                <input asp-for="ExhibitId" class="form-control" />
                <span asp-validation-for="ExhibitId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="RatingValue" class="control-label"></label>
                <input asp-for="RatingValue" class="form-control" />
                <span asp-validation-for="RatingValue" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FLL/Views/Ratings/Delete.cshtml
@model FLL.Models.Rating

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rating</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExhibitId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExhibitId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RatingValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RatingValue)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RatingId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FLL/Views/Ratings/Details.cshtml
@model FLL.Models.Rating

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Rating</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExhibitId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExhibitId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RatingValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RatingValue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.RatingId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FLL/Views/Ratings/Edit.cshtml
@model FLL.Models.Rating

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Rating</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RatingId" />
            <div class="mb-3">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ExhibitId" class="control-label"></label>
                <input asp-for="ExhibitId" class="form-control" />
                <span asp-validation-for="ExhibitId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="RatingValue" class="control-label"></label>
                <input asp-for="RatingValue" class="form-control" />
                <span asp-validation-for="RatingValue" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FLL/Views/Ratings/Index.cshtml
@model IEnumerable<FLL.Models.Rating>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExhibitId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RatingValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExhibitId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RatingValue)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RatingId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RatingId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RatingId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FLL/Views/Ratings/LeaveMessage.cshtml
@model Rating

<p>Would you like to leave a message?</p>
<form method="post" asp-controller="Ratings" asp-action="UpdateRatingMessage" asp-route-ratingId="@Model.RatingId">
    <label asp-for="@Model.Message" class="form-label"></label> <br />
    <textarea asp-for="@Model.Message" class="form-control"></textarea> <br />
    <button type="submit" class="btn btn-primary mt-3">Continue</button>
</form>

FLL/Views/Ratings/ThankYou.cshtml
<h1>Thank you for leaving a review!</h1>

<a asp-controller="Home" asp-action="Index" class="btn btn-success">Go To Home</a>